apiVersion: v1
kind: Pod
metadata:
  name: crash-pod
  labels:
    app: crash-test
spec:
  containers:
    - name: crash-container
      image: busybox
      command: ["sh", "-c", "echo Crash Test; sleep 10; exit 1"]